name: Official SonarQube Scan
description: >
  Scan your code with SonarQube to detect Bugs, Vulnerabilities and Code Smells in up to 27 programming languages!
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"
  args:
    - ${{ inputs.baseImage }}
inputs:
  args:
    description: Additional arguments to the sonar-scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
  baseImage:
    description: Allow for a different base image to be used from a private registry to avoid rate limiting.
    required: false
