name: Forked from official SonarQube Scan
description: >
  Scan your code with SonarQube to detect Bugs, Vulnerabilities and Code Smells in up to 27 programming languages!
branding:
  icon: check
  color: green
inputs:
  args:
    description: Additional arguments to the sonar-scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
  base_image:
    required: false
    description: 'Provide a base image of sonarsource/sonar-scanner-cli that is hosted on your own registry'
  docker_username:
    required: false
  docker_password:
    required: false
runs:
  using: docker
  image: Dockerfile
  args: 
    - ${{ inputs.base_image }}
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"
  credentials: 
    username: ${{ inputs.docker_username }}
    password: ${{ inputs.docker_password }}
